import dynamic from "next/dynamic";
import Head from "next/head";
import { useCollectPoint } from "@/utils/context/CollectPoint";

const Map = dynamic(() => import("@/components/Map"), { ssr: false });
const Header = dynamic(() => import("@/components/Header"), { ssr: false });
const BoxPartners = dynamic(() => import("@/sections/BoxPartners"), {
  ssr: false,
});
const CardOng = dynamic(() => import("@/components/CardOng"), { ssr: false });

export default function Home() {
  const { collectPointId } = useCollectPoint();
  return (
    <>
      <Head>
        <title>Projeto Nutrir</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <Map />
      <BoxPartners />
      {collectPointId && <CardOng />}
    </>
  );
}
