import dynamic from "next/dynamic";
import Head from "next/head";

const Header = dynamic(() => import("@/components/Header"), { ssr: false });
const PageSobre = dynamic(() => import("@/sections/Sobre"), { ssr: false });

export default function Sobre() {
  return (
    <>
      <Head>
        <title>Projeto Nutrir - Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <PageSobre />
    </>
  );
}
